// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ortymid/market/market/product (interfaces: Interface)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	product "github.com/ortymid/market/market/product"
	reflect "reflect"
)

// ProductService is a mock of Interface interface
type ProductService struct {
	ctrl     *gomock.Controller
	recorder *ProductServiceMockRecorder
}

// ProductServiceMockRecorder is the mock recorder for ProductService
type ProductServiceMockRecorder struct {
	mock *ProductService
}

// NewProductService creates a new mock instance
func NewProductService(ctrl *gomock.Controller) *ProductService {
	mock := &ProductService{ctrl: ctrl}
	mock.recorder = &ProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *ProductService) EXPECT() *ProductServiceMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *ProductService) Create(arg0 context.Context, arg1 product.CreateRequest) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *ProductServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*ProductService)(nil).Create), arg0, arg1)
}

// Delete mocks base method
func (m *ProductService) Delete(arg0 context.Context, arg1 string) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete
func (mr *ProductServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*ProductService)(nil).Delete), arg0, arg1)
}

// Find mocks base method
func (m *ProductService) Find(arg0 context.Context, arg1 product.FindRequest) ([]*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].([]*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *ProductServiceMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*ProductService)(nil).Find), arg0, arg1)
}

// FindOne mocks base method
func (m *ProductService) FindOne(arg0 context.Context, arg1 string) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne
func (mr *ProductServiceMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*ProductService)(nil).FindOne), arg0, arg1)
}

// Update mocks base method
func (m *ProductService) Update(arg0 context.Context, arg1 product.UpdateRequest) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *ProductServiceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*ProductService)(nil).Update), arg0, arg1)
}
