// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ortymid/market/market/product (interfaces: Storage)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	product "github.com/ortymid/market/market/product"
	reflect "reflect"
)

// MockProductStorage is a mock of Storage interface
type MockProductStorage struct {
	ctrl     *gomock.Controller
	recorder *MockProductStorageMockRecorder
}

// MockProductStorageMockRecorder is the mock recorder for MockProductStorage
type MockProductStorageMockRecorder struct {
	mock *MockProductStorage
}

// NewMockProductStorage creates a new mock instance
func NewMockProductStorage(ctrl *gomock.Controller) *MockProductStorage {
	mock := &MockProductStorage{ctrl: ctrl}
	mock.recorder = &MockProductStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProductStorage) EXPECT() *MockProductStorageMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockProductStorage) Create(arg0 context.Context, arg1 product.CreateRequest) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockProductStorageMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductStorage)(nil).Create), arg0, arg1)
}

// Delete mocks base method
func (m *MockProductStorage) Delete(arg0 context.Context, arg1 string) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete
func (mr *MockProductStorageMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductStorage)(nil).Delete), arg0, arg1)
}

// Get mocks base method
func (m *MockProductStorage) Get(arg0 context.Context, arg1 string) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockProductStorageMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProductStorage)(nil).Get), arg0, arg1)
}

// List mocks base method
func (m *MockProductStorage) List(arg0 context.Context, arg1 product.ListRequest) ([]*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockProductStorageMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProductStorage)(nil).List), arg0, arg1)
}

// Update mocks base method
func (m *MockProductStorage) Update(arg0 context.Context, arg1 product.UpdateRequest) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockProductStorageMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductStorage)(nil).Update), arg0, arg1)
}
