version: "3"

services:
  http_gateway:
    build: 
      context: .
      dockerfile: ./cmd/httpgateway/Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - http_user_service

  grpc_server:
    build: 
      context: .
      dockerfile: ./cmd/grpcserver/Dockerfile
    env_file: .env
    ports:
      - 8081:8081
    depends_on:
      - http_user_service

  http_user_service:
    build: ~/Projects/Sigma/Internship/peers/AiexMoran/httpCRUD
    env_file: ~/Projects/Sigma/Internship/peers/AiexMoran/httpCRUD/.env
    ports:
      - 8888:8888
